apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  jwt-secret: cmlkYW5Eb2FuZ1lhbmdLZXJqYWlu
  google-client-id: OTEwMDA3Mjc1ODYxLTU4NWNqZzlvNW9rZjB0Y25nbmNpMDRjZnFvcHZjZW5zLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  google-client-secret: R09DU1BYLUNvSV9Dcllpd1VIZmpEMFdqSmlqNVRtUnFfQjU=
