apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: pencarisalmon/auth-service:v1
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://root:ridanKetuaBayangan@mongodb:27017/farmDb?authSource=admin"
            - name: AUTH_SERVICE_PORT
              value: "3000"
            - name: JWT_EXPIRES_IN
              value: "1h"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: google-client-secret
