apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: pencarisalmon/product-service:v1
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: "mongodb://root:ridanKetuaBayangan@mongodb:27017/farmDb?authSource=admin"
            - name: PRODUCT_SERVICE_PORT
              value: "4000"